# Generated by Django 5.2.5 on 2026-06-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('galaxy', models.PositiveIntegerField(default=1)),
                ('system', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('metal', models.BigIntegerField(default=500)),
                ('crystal', models.BigIntegerField(default=200)),
                ('helion', models.BigIntegerField(default=0)),
                ('metal_production_remainder_micro', models.PositiveIntegerField(default=0)),
                ('crystal_production_remainder_micro', models.PositiveIntegerField(default=0)),
                ('helion_production_remainder_micro', models.PositiveIntegerField(default=0)),
                ('is_homeland', models.BooleanField(default=False)),
                ('last_resource_update', models.DateTimeField(auto_now_add=True)),
                ('planet_fields_total', models.PositiveIntegerField(default=90)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['galaxy', 'system', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.BigIntegerField(default=0)),
                ('crystal', models.BigIntegerField(default=0)),
                ('helion_cost', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('outbound', 'Outbound'), ('returning', 'Returning'), ('completed', 'Completed')], default='outbound', max_length=20)),
                ('mission_type', models.CharField(choices=[('transport', 'Transport'), ('station', 'Station')], default='transport', max_length=30)),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField()),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to=settings.AUTH_USER_MODEL)),
                ('source_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_fleets', to='game.planet')),
                ('target_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_fleets', to='game.planet')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_mine_level', models.PositiveIntegerField(default=1)),
                ('crystal_mine_level', models.PositiveIntegerField(default=0)),
                ('helion_synthesizer_level', models.PositiveIntegerField(default=0)),
                ('metal_storage_level', models.PositiveIntegerField(default=1)),
                ('crystal_storage_level', models.PositiveIntegerField(default=1)),
                ('helion_storage_level', models.PositiveIntegerField(default=0)),
                ('shipyard_level', models.PositiveIntegerField(default=0)),
                ('building_type', models.CharField(blank=True, default='', max_length=50)),
                ('building_ends_at', models.DateTimeField(blank=True, null=True)),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.planet')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_code', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='game.planet')),
            ],
            options={
                'ordering': ['planet_id', 'ship_code'],
            },
        ),
        migrations.CreateModel(
            name='PlanetShipConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_code', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ship_construction', to='game.planet')),
            ],
        ),
        migrations.CreateModel(
            name='FleetShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_code', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='game.fleet')),
            ],
            options={
                'ordering': ['fleet_id', 'ship_code'],
                'constraints': [models.UniqueConstraint(fields=('fleet', 'ship_code'), name='unique_ship_type_per_fleet')],
            },
        ),
        migrations.AddConstraint(
            model_name='planet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_homeland', True)), fields=('owner',), name='unique_homeland_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='planet',
            constraint=models.UniqueConstraint(fields=('galaxy', 'system', 'position'), name='unique_planet_coordinates'),
        ),
        migrations.AddConstraint(
            model_name='planetship',
            constraint=models.UniqueConstraint(fields=('planet', 'ship_code'), name='unique_ship_type_per_planet'),
        ),
    ]
