# Generated by Django 5.2.5 on 2026-04-14 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('metal', models.BigIntegerField(default=500)),
                ('crystal', models.BigIntegerField(default=200)),
                ('metal_mine_level', models.PositiveIntegerField(default=1)),
                ('crystal_mine_level', models.PositiveIntegerField(default=0)),
                ('metal_storage_level', models.PositiveIntegerField(default=1)),
                ('crystal_storage_level', models.PositiveIntegerField(default=1)),
                ('is_homeland', models.BooleanField(default=False)),
                ('last_resource_update', models.DateTimeField(auto_now_add=True)),
                ('building_type', models.CharField(blank=True, default='', max_length=50)),
                ('building_ends_at', models.DateTimeField(blank=True, null=True)),
                ('transporter_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['x', 'y'],
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_count', models.BigIntegerField()),
                ('metal', models.BigIntegerField(default=0)),
                ('crystal', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('outbound', 'Outbound'), ('returning', 'Returning'), ('completed', 'Completed')], default='outbound', max_length=20)),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField()),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to=settings.AUTH_USER_MODEL)),
                ('source_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_fleets', to='game.planet')),
                ('target_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_fleets', to='game.planet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='planet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_homeland', True)), fields=('owner',), name='unique_homeland_per_owner'),
        ),
    ]
